# Generated by Django 3.2.6 on 2021-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField()),
                ('specifications', models.CharField(max_length=50)),
                ('authorizedPerson', models.CharField(max_length=50)),
                ('review', models.IntegerField()),
            ],
        ),
    ]
