# Generated by Django 3.2.6 on 2021-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.IntegerField(default=5),
        ),
    ]
