# Generated by Django 2.1.3 on 2021-11-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethods', '0002_auto_20211117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
